[package]
name = "tree-sitter-acds"
description = "Tree-sitter grammar for ABAP CDS"
version = "0.1.0"
authors = ["Kendrick Hommel <kendrick.hommel@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "acds"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/kennyhml/tree-sitter-acds"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "grammar/*",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.9"
